[book]
authors = ["Kurt Pan"]
language = "en"

src = "src"
title = "密碼聖典"


[output.html]
theme = "theme"
additional-css = ["theme/custom-fonts.css"]

[output.html.search]
enable = false

[output.html.print]
enable = false

[output.html.fold]
enable = true   # whether or not to enable section folding
level = 0        # the depth to start folding
